# Generated by Django 5.1 on 2024-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softv", "0003_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("TV", "TV"),
                    ("Phone", "Phone"),
                    ("Speaker", "Speaker"),
                    ("Laptop", "Laptop"),
                ],
                max_length=100,
            ),
        ),
    ]
