# Generated by Django 5.1 on 2024-08-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softv', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TV', 'TV'), ('Phone', 'Phone'), ('Speaker', 'Speaker'), ('Laptop', 'Laptop')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
