# Generated by Django 5.1 on 2024-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softv', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
