# Generated by Django 5.1 on 2024-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softv', '0011_liked_date_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
    ]
