# Generated by Django 5.1 on 2024-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softv', '0012_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
