"""
Django settings for softvision project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
# settings.py
LOGIN_URL = '/login/'  # or the URL where your login page is located


SECRET_KEY = "django-insecure-r#3#pi#kr2=xb2w+o&+yjymue1_wtqrv&fk*#ds09vx+otr1j9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Add this to your urlpatterns
import django
print(django.__path__)

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "softv.apps.SoftvConfig",
    'accounts',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = "softvision.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "softvision.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"




import smtplib
import ssl
import stripe

EMAIL_HOST_USER='bharatsingh87368@gmail.com'
EMAIL_HOST_PASSWORD='qrzt cjtv smdn utzl'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

context = ssl._create_unverified_context()
class CustomSMTP(smtplib.SMTP):
    def starttls(self, *args, **kwargs):
        super().starttls(context=context)


smtplib.SMTP = CustomSMTP



STRIPE_SECRET_KEY='sk_test_51PzhmKKUMuayZaJ0JkON4NgqcSxqzXlj2hbQcouNo2NkPSK9bRt7A6lAfKu5UvlT9I2yaYZ4AUkOSuU8UhYDkaDz00Pn1mxteE'
STRIPE_PUBLISHABLE_KEY='pk_test_51PzhmKKUMuayZaJ0l8J1miAXCoiajxS6220Y31bYq7nR9BJmQebYRQsUYTrkvTIFF4Augb7quDoDYNgyuSo4aNFj00lDAK4TYS'